import { useEffect, useRef, useState } from 'react';
import { Camera, FileImage, LoaderCircle, X } from 'lucide-react';
import { prepareImageUpload } from '../utils/imageProcessing';
import { recognizeFormulaContent } from '../services/api';
import type { RecognizedBlock, RecognizedContent } from '../types';
import RecognizedContentCard from './formula/RecognizedContentCard';

interface Props { token?: string | null; onPhotoQuestion: (image: string) => void; onInsert: (blocks: RecognizedBlock[]) => void; onClose: () => void; }
export default function PhotoPreviewSheet({ token, onPhotoQuestion, onInsert, onClose }: Props) {
  const inputRef = useRef<HTMLInputElement>(null); const cameraRef = useRef<HTMLInputElement>(null); const [image, setImage] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [result, setResult] = useState<RecognizedContent | null>(null); const abortRef = useRef<AbortController | null>(null);
  useEffect(() => () => abortRef.current?.abort(), []);
  const choose = () => inputRef.current?.click(); const chooseCamera = () => cameraRef.current?.click();
  const onFile = async (file?: File) => { if (!file) return; setError(''); try { const reader = new FileReader(); reader.onload = async () => { try { const data = String(reader.result); const blob = await prepareImageUpload(data); const url = URL.createObjectURL(blob); const img = new Image(); img.onload = () => { const c = document.createElement('canvas'); c.width = img.width; c.height = img.height; c.getContext('2d')?.drawImage(img, 0, 0); setImage(c.toDataURL('image/jpeg', .92)); URL.revokeObjectURL(url); }; img.src = url; } catch (e) { setError(e instanceof Error ? e.message : '图片无法解码，请改选 JPEG/PNG'); } }; reader.readAsDataURL(file); } catch (e) { setError(e instanceof Error ? e.message : '图片读取失败'); } };
  const recognize = async () => { if (!image || busy) return; setBusy(true); setError(''); const controller = new AbortController(); abortRef.current = controller; try { setResult(await recognizeFormulaContent(image, token || undefined, controller.signal)); } catch (e) { if (!controller.signal.aborted) setError(e instanceof Error ? e.message : '识别失败，请重试'); } finally { setBusy(false); abortRef.current = null; } };
  if (result) return <RecognizedContentCard image={image} blocks={result.blocks} warnings={result.warnings} onInsert={onInsert} onRetry={() => { setResult(null); void recognize(); }} onPhotoQuestion={() => onPhotoQuestion(image)} onClose={onClose} />;
  return <div className="fixed inset-0 z-[105] grid place-items-center bg-slate-950/50 p-3"><section className="w-[min(520px,100%)] rounded-xl bg-white p-4 shadow-2xl dark:bg-slate-900" role="dialog" aria-label="图片预览"><header className="flex items-center justify-between"><h3 className="text-sm font-semibold">图片预览</h3><button type="button" onClick={onClose} aria-label="关闭" className="icon-button"><X className="h-4 w-4" /></button></header><input ref={inputRef} type="file" accept="image/*" className="hidden" onChange={e => void onFile(e.target.files?.[0])} /><input ref={cameraRef} type="file" accept="image/*" capture="environment" className="hidden" onChange={e => void onFile(e.target.files?.[0])} />{image ? <img src={image} alt="待识别图片" className="mt-3 max-h-[55dvh] w-full rounded-lg object-contain" /> : <div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={chooseCamera} className="flex h-32 flex-col items-center justify-center rounded-lg border border-dashed border-slate-300 text-sm text-slate-500"><Camera className="mb-2 h-7 w-7" />拍照</button><button type="button" onClick={choose} className="flex h-32 flex-col items-center justify-center rounded-lg border border-dashed border-slate-300 text-sm text-slate-500"><FileImage className="mb-2 h-7 w-7" />相册</button></div>}{error && <p className="mt-3 text-xs text-rose-600">{error}</p>}<div className="mt-4 flex flex-wrap justify-end gap-2"><button type="button" onClick={choose} className="toolbar-button"><FileImage className="h-4 w-4" />更换图片</button><button type="button" onClick={() => onPhotoQuestion(image)} disabled={!image} className="toolbar-button">拍题提问</button><button type="button" onClick={() => void recognize()} disabled={!image || busy} className="toolbar-button toolbar-button-primary">{busy && <LoaderCircle className="h-4 w-4 animate-spin" />}识别公式</button></div></section></div>;
}
