services:
  api:
    build:
      context: ..
      dockerfile: deploy/backend/Dockerfile
  web:
    build:
      context: ..
      dockerfile: deploy/frontend/Dockerfile
  manim-renderer:
    build:
      context: ..
      dockerfile: deploy/manim/Dockerfile
